import type { QrTemplate } from '../types/qr-options';

export const QR_TEMPLATES: QrTemplate[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Clean black-on-white square QR with no effects.',
    overrides: {
      dotType: 'square',
      dotColor: '#000000',
      dotGradient: undefined,
      cornerSquareType: 'square',
      cornerSquareColor: '#000000',
      cornerSquareGradient: undefined,
      cornerDotType: 'square',
      cornerDotColor: '#000000',
      cornerDotGradient: undefined,
      backgroundColor: '#ffffff',
      backgroundGradient: undefined,
      backgroundRound: 0,
      shape: 'square',
      imageSize: 0.4,
      imageMargin: 0,
      hideBackgroundDots: true,
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
  {
    id: 'rounded-modern',
    name: 'Rounded Modern',
    description: 'Smooth rounded dots with a sleek linear gradient.',
    overrides: {
      dotType: 'rounded',
      dotGradient: {
        type: 'linear',
        rotation: 45,
        colorStops: [
          { offset: 0, color: '#1a1aff' },
          { offset: 1, color: '#00ccff' },
        ],
      },
      cornerSquareType: 'extra-rounded',
      cornerSquareColor: '#1a1aff',
      cornerDotType: 'dot',
      cornerDotColor: '#00ccff',
      backgroundColor: '#ffffff',
      backgroundRound: 0,
      shape: 'square',
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
  {
    id: 'sunset-gradient',
    name: 'Sunset Gradient',
    description: 'Warm orange-to-pink gradient with classy-rounded style.',
    overrides: {
      dotType: 'classy-rounded',
      dotGradient: {
        type: 'linear',
        rotation: 135,
        colorStops: [
          { offset: 0, color: '#ff6600' },
          { offset: 1, color: '#ff0066' },
        ],
      },
      cornerSquareType: 'extra-rounded',
      cornerSquareColor: '#ff6600',
      cornerDotType: 'dot',
      cornerDotColor: '#ff0066',
      backgroundColor: '#fff9f0',
      backgroundRound: 0,
      shape: 'square',
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
  {
    id: 'ocean-dots',
    name: 'Ocean Dots',
    description: 'Blue dots gradient in a circular QR shape.',
    overrides: {
      dotType: 'dots',
      dotGradient: {
        type: 'radial',
        rotation: 0,
        colorStops: [
          { offset: 0, color: '#0099ff' },
          { offset: 1, color: '#003399' },
        ],
      },
      cornerSquareType: 'dot',
      cornerSquareColor: '#0099ff',
      cornerDotType: 'dot',
      cornerDotColor: '#003399',
      backgroundColor: '#f0f8ff',
      backgroundRound: 0,
      shape: 'circle',
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
  {
    id: 'elegant-shadow',
    name: 'Elegant Shadow',
    description: 'Classy style with a subtle drop shadow for depth.',
    overrides: {
      dotType: 'classy',
      dotColor: '#1a1a1a',
      dotGradient: undefined,
      cornerSquareType: 'square',
      cornerSquareColor: '#1a1a1a',
      cornerDotType: 'dot',
      cornerDotColor: '#1a1a1a',
      backgroundColor: '#ffffff',
      backgroundRound: 0,
      shape: 'square',
      shadow: { enabled: true, color: '#000000', opacity: 0.25, blur: 12, offsetX: 4, offsetY: 4 },
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Bright neon green on dark background in circular form.',
    overrides: {
      dotType: 'dots',
      dotColor: '#00ff88',
      dotGradient: undefined,
      cornerSquareType: 'dot',
      cornerSquareColor: '#00ff88',
      cornerDotType: 'dot',
      cornerDotColor: '#00ff88',
      backgroundColor: '#111111',
      backgroundRound: 0,
      shape: 'circle',
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
  {
    id: 'purple-glow',
    name: 'Purple Glow',
    description: 'Purple gradient with a glowing drop shadow.',
    overrides: {
      dotType: 'rounded',
      dotGradient: {
        type: 'linear',
        rotation: 135,
        colorStops: [
          { offset: 0, color: '#8800ff' },
          { offset: 1, color: '#cc44ff' },
        ],
      },
      cornerSquareType: 'extra-rounded',
      cornerSquareColor: '#8800ff',
      cornerDotType: 'dot',
      cornerDotColor: '#cc44ff',
      backgroundColor: '#1a0033',
      backgroundRound: 0,
      shape: 'square',
      shadow: { enabled: true, color: '#8800ff', opacity: 0.5, blur: 20, offsetX: 0, offsetY: 0 },
    },
  },
  {
    id: 'glossy-purple',
    name: 'Glossy Purple',
    description: 'Rounded glossy purple corners with radial gradients for a 3D look.',
    overrides: {
      dotType: 'extra-rounded',
      dotGradient: {
        type: 'radial',
        rotation: 0,
        colorStops: [
          { offset: 0, color: '#B07AEA' },
          { offset: 1, color: '#6B21A8' },
        ],
      },
      cornerSquareType: 'extra-rounded',
      cornerSquareColor: '#7C3AED',
      cornerSquareGradient: {
        type: 'radial',
        rotation: 0,
        colorStops: [
          { offset: 0, color: '#B07AEA' },
          { offset: 1, color: '#6B21A8' },
        ],
      },
      cornerDotType: 'extra-rounded',
      cornerDotColor: '#7C3AED',
      cornerDotGradient: {
        type: 'radial',
        rotation: 0,
        colorStops: [
          { offset: 0, color: '#C4A0F0' },
          { offset: 1, color: '#7C3AED' },
        ],
      },
      backgroundColor: '#ffffff',
      backgroundGradient: undefined,
      backgroundRound: 0,
      shape: 'square',
      imageSize: 0.4,
      imageMargin: 0,
      hideBackgroundDots: true,
      shadow: { enabled: false, color: '#000000', opacity: 0.3, blur: 10, offsetX: 3, offsetY: 3 },
    },
  },
];
